### ISSUE TITLE
Crash upon saving when selecting MenuTopic course format

### ISSUE THREAD

**Issue by jamesdean2077** [davidherney/moodle-format_menutopic#21] opened 2023-11-15 20:03 UTC
Upon saving the course page after selecting "MenuTopic" course format, the error comes up (Boost theme)..

Not sure how to enable or disable the MenuTopic block (not shown in block list?) according to line 734: $showsection = true;  ??

```
Warning: Undefined property: format_menutopic::$page in /var/www/moodle/course/format/menutopic/lib.php on line 734

Error
Exception - Call to a member function user_is_editing() on null
Debug info:
Error code: generalexceptionmessage
Stack trace:
line 734 of /course/format/menutopic/lib.php: Error thrown
line 60 of /course/format/menutopic/classes/header.php: call to format_menutopic->load_formatdata()
line 266 of /lib/outputrenderers.php: call to format_menutopic\header->export_for_template()
line 531 of /lib/outputrenderers.php: call to renderer_base->render()
line 108 of /course/format/classes/output/section_renderer.php: call to plugin_renderer_base->render()
line 1626 of /lib/outputrenderers.php: call to core_courseformat\output\section_renderer->render()
line 219 of /lib/mustache/src/Mustache/Context.php: call to core_renderer->course_content_header()
line 138 of /lib/mustache/src/Mustache/Context.php: call to Mustache_Context->findVariableInStack()
line 84 of data/localcache/mustache/1700076007/boost/__Mustache_4aa1b29b14b62e9eb02cc88038b79589.php: call to Mustache_Context->findDot()
line 66 of /lib/mustache/src/Mustache/Template.php: call to __Mustache_4aa1b29b14b62e9eb02cc88038b79589->renderInternal()
line 208 of /lib/outputrenderers.php: call to Mustache_Template->render()
line 107 of /theme/boost/layout/drawers.php: call to renderer_base->render_from_template()
line 1486 of /lib/outputrenderers.php: call to include()
line 1412 of /lib/outputrenderers.php: call to core_renderer->render_page_layout()
line 290 of /course/view.php: call to core_renderer->header()
```

I had to tentatively rename lib.php file in order to bring the course back online and roll back to a different course format. 

Thank you for this cool plugin!

**Comment by davidherney** [comment] 2023-11-15 21:38
Hi @jamesdean2077 

What is your Moodle version? What version of the plugin are you using?

PD: Menutopic is not a block, it is a Course format.

Saludos

**Comment by jamesdean2077** [comment] 2023-11-16 19:54
Thank you @davidherney for your time looking into this - am running Moodle 4.3+ (Build: 20231110) on PHP 8.2.11. 

As for plugin version - I have michelle-4.0.2 (Build 2023050702) installed from the Moodle plugin repo. 

Indeed, Menutopic is a course format plugin, I misunderstood about $section being shown as block (line 732-736 in lib.php). 

This got me thinking - I have the announcement section removed/hidden (Section 0) - would that be the cause for this error?

**Comment by davidherney** [comment] 2023-11-16 23:22
Hi @jamesdean2077 ...

I have not yet tested the format with Moodle 4.3. It is tested for Moodle 4.1.

Moodle >= 4.2 has several important changes to the course formats. I need a little more time to implement them. The error is probably due to one of those changes.

I will try to have compatibility as soon as possible.

Saludos

**Comment by jamesdean2077** [comment] 2023-11-18 19:54
Yes, lot of changes going on with moving over to Moodle 4.x and PHP 8.. I'd be happy to help with testing, @davidherney.

Saludos cordiales

**Comment by florent-dev** [comment] 2024-03-29 17:30
> Hi @jamesdean2077 ...
> 
> I have not yet tested the format with Moodle 4.3. It is tested for Moodle 4.1.
> 
> Moodle >= 4.2 has several important changes to the course formats. I need a little more time to implement them. The error is probably due to one of those changes.
> 
> I will try to have compatibility as soon as possible.
> 
> Saludos

Hello, I can reproduce this issue on Moodle 4.1

```
Error
Exception : Call to a member function user_is_editing() on null
Debug info:
Error code: generalexceptionmessage
Stack trace:
line 734 of /course/format/menutopic/lib.php: Error thrown
line 60 of /course/format/menutopic/classes/header.php: call to format_menutopic->load_formatdata()
line 266 of /lib/outputrenderers.php: call to format_menutopic\header->export_for_template()
line 531 of /lib/outputrenderers.php: call to renderer_base->render()
line 108 of /course/format/classes/output/section_renderer.php: call to plugin_renderer_base->render()
line 1591 of /lib/outputrenderers.php: call to core_courseformat\output\section_renderer->render()
line 219 of /lib/mustache/src/Mustache/Context.php: call to core_renderer->course_content_header()
line 138 of /lib/mustache/src/Mustache/Context.php: call to Mustache_Context->findVariableInStack()
line 109 of /tempdata/localcache/mustache/1711681659/moove/__Mustache_127af54580c2a918e814de70b54aeb5d.php: call to Mustache_Context->findDot()
line 67 of /lib/mustache/src/Mustache/Template.php: call to __Mustache_127af54580c2a918e814de70b54aeb5d->renderInternal()
line 208 of /lib/outputrenderers.php: call to Mustache_Template->render()
line 134 of /theme/moove/layout/course.php: call to renderer_base->render_from_template()
line 1477 of /lib/outputrenderers.php: call to include()
line 1403 of /lib/outputrenderers.php: call to core_renderer->render_page_layout()
line 248 of /course/view.php: call to core_renderer->header()
```

Here are some details about Moodle :
- Moodle 4.1.9 (Build: 20240212)
- PHP Version 8.1.27

Maybe we could check $this->page before calling its method user_is_editing() ?
`} else if ($section == 0 && !($thissection->summary || $thissection->sequence || ($this->page && $this->user_is_editing()))) {`
line 734, file lib.php

Thanks in advance for your help.

Florent

**Comment by davidherney** [comment] 2024-05-20 01:53
Hi...

Resolved in the las commit.

Saludos

**Closed by davidherney** 2024-05-20 01:53 UTC
